/*CREATION OF DB*/
CREATE SCHEMA LOUDBITES;
ALTER SCHEMA `LOUDBITES` DEFAULT COLLATE utf8_general_ci;

CREATE USER 'loudbitesdbu'@'127.0.0.1' IDENTIFIED BY 'loudbites1234';
/*Grant permission only to this DB*/
GRANT SELECT,INSERT,UPDATE ON FLOWERS.* TO 'loudbitesdbu'@'127.0.0.1' WITH GRANT OPTION;

/*Change to DB*/
USE LOUDBITES;

/*ACCOUNTS table*/
CREATE TABLE `ACCOUNTS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USRNME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(200) NULL,
  `PSSWRD` VARCHAR(45) NULL,
  `STTS` VARCHAR(10) NULL DEFAULT 'pending',
  `EMAIL_NWSLTTR_STTS` VARCHAR(3) NULL DEFAULT 'out',
  `EMAIL_TYPE` VARCHAR(4) NULL DEFAULT 'text',
  `EMAIL_FVRT_ARTST_STTS` VARCHAR(3) NULL DEFAULT 'out',
  `CRTD_DT` DATETIME NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `USRNME_UNIQUE` (`USRNME` ASC))
AUTO_INCREMENT = 1;

/*ARTISTS table*/
CREATE TABLE `ARTISTS` (
  `ID` INT NOT NULL,
  `ARTST_NME` VARCHAR(200) NOT NULL,
  `GNRE` VARCHAR(45) NOT NULL,
  `CRTD_DT` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `UNIQUE_ARTST` (`ARTST_NME` ASC, `GNRE` ASC))
AUTO_INCREMENT = 1;

/*ACCOUNT_ARTISTS table*/
CREATE TABLE `ACCOUNT_ARTISTS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ACCNT_ID` INT NULL,
  `ARTST_ID` INT NULL,
  `CRTD_DT` DATETIME NULL,
  `RTNG` INT NULL,
  `IS_FAV` INT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
AUTO_INCREMENT = 1;
